# -*- coding: utf-8 -*-
"""tictactoe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vesS8HzWJhO5aj3g48U-7PO2DfIcUd5y
"""

def analyseboard(board):
  c=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
  for i in range(0,8):
    if(board[c[i][0]]>=0 and board[c[i][0]]==board[c[i][1]] and board[c[i][1]]== board[c[i][2]]):
      return board[c[i][0]]
  return 0
def constboard(board):
  print("the current state of the board:\n\n")
  for i in range(0,9):
    if((i>0)and (i%3==0)):
      print("\n")
    if(board[i]==0):
     print("_",end=" ")
    if(board[i]==1):
      print("O",end=" ")
    if(board[i]==-1):
      print("X",end=" ")
  print("\n\n")
def user1turn(board):
  pos=input("Enter X position [1-9]:")
  pos=int(pos)
  if(board[pos-1]!=0):
    print("wrong move")
    exit(0)#in built function which ends the whole program no further execution
  board[pos-1]=-1
def user2turn(board):
  pos=input("Enter O position [1-9]:")
  pos=int(pos)
  if(board[pos-1]!=0):
    print("wrong move")
    exit(0)#in built function which ends the whole program no further execution
  board[pos-1]=1
def minmax(board,player):
  x=analyseboard(board)
  if(x!=0):
    return (x*player)
  pos=-1
  value=-2
  for i in range(0,9):
    if(board[i]==0):
      board[i]=player
      score=-minmax(board,player*-1)
      board[i]=0
      if(score>value):
        value=score
        pos=i
  if(pos==-1):
    return 0
  return value


def compturn(board):
  pos=-1
  value=-2
  for i in range(0,9):
    if(board[i]==0):
      board[i]=1
      score=-minmax(board,-1)
      board[i]=0
      if(score>value):
        value=score
        pos=i
  board[pos]=1


def main():
  choice=input("Enter 1 for SinglePlayer and 2 for MultiPlayer: ")
  choice=int(choice)
  board=[0,0,0,0,0,0,0,0,0]
  if(choice==1):
    print("Computer:O Vs You:X")
    player=input("enter to play 1st('1') or 2nd('2')")
    player=int(player)
    for i in range(0,9):
      if(analyseboard(board)!=0):
        break
      if((i+player)%2==0):
        compturn(board)
      else:
        constboard(board)
        user1turn(board)
  else:
    #multiplayer part
    for i in range(0,9):
      if(analyseboard(board)!=0):
        break
      if(i%2==0):
        constboard(board)
        user1turn(board)
      else:
        constboard(board)
        user2turn(board)
  constboard(board)
  if(analyseboard(board)==0):
    print("Draw!")
  elif(analyseboard(board)==-1):
    constboard(board)
    print("player 1 has won the game")
  else:
    constboard(board)
    print("player 2 has won the game")